base_url: https://practice.expandtesting.com/notes/app
api_base_url: https://practice.expandtesting.com/notes/api

execution_mode: remote   # local | remote | browserstack | lambdatest

grid_url: http://localhost:4444/wd/hub

browser: chrome   # chrome | firefox | edge

credentials:
  username: charithreddy2004@gmail.com
  password: Charith@2004

openai:
  api_key: ak_2AA5jV2wf3UL18J3aL6wQ1Db6fl4e